export const lehngacholiPage2=[
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/y/g/m/l-sleeveless-shset95222-shae-by-sassafras-original-imaggjzkwyyyezzg.jpeg?q=70",
    brand: "Shae by SASSAFRAS",
    title: "Printed Stitched Lehenga Choli",
    color: "Grey",
    selling_price: "₹2,069",
    price: "₹4,599",
    disscount: "55% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/knyxqq80/salwar-kurta-dupatta/q/i/q/32-skd7385-biba-original-imag2jag2zzz3shw.jpeg?q=70",
    brand: "BIBA",
    title: "Solid Stitched Lehenga Choli",
    color: "Yellow",
    selling_price: "₹4,016",
    price: "₹8,995",
    disscount: "55% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/krme93k0/lehenga-choli/9/t/e/free-half-sleeve-ghaghra-choli-coconut-original-imag5df5ktsnnypv.jpeg?q=70",
    brand: "ZAALIMA FASHION",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Green",
    selling_price: "₹386",
    price: "₹1,799",
    disscount: "78% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/l/x/d/free-full-sleeve-lehenga-lehenga-for-women-lehenga-choli-net-original-imaggcwfb3pjh2hf.jpeg?q=70",
    brand: "Cute Fellow",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Purple",
    selling_price: "₹615",
    price: "₹3,499",
    disscount: "82% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/kp78e4w0/lehenga-choli/n/n/d/free-short-sleeve-baby-pink-choli-trivety-original-imag3hbpwczdj2hu.jpeg?q=70",
    brand: "Trivety",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Pink",
    selling_price: "₹439",
    price: "₹1,999",
    disscount: "78% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/g/0/m/free-sleeveless-zip1434-zinariya-fab-original-imagnftyaaaqjexa.jpeg?q=70",
    brand: "Zinariya Fab",
    title: "Floral Print Semi Stitched Lehenga Choli",
    color: "Blue",
    selling_price: "₹499",
    price: "₹3,099",
    disscount: "83% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/l29c9e80/lehenga-choli/w/c/v/free-sleeveless-gulab02-rhet-fashion-original-imagdmy4cnbc839p.jpeg?q=70",
    brand: "jahal fashion",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Red",
    selling_price: "₹484",
    price: "₹2,499",
    disscount: "80% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/l1fc0i80/lehenga-choli/j/k/t/free-half-sleeve-modak-rama-gajri-dishwa-fashion-original-imagczmhzqmzpyy9.jpeg?q=70",
    brand: "DECIZE CLOTHING",
    title: "Self Design Semi Stitched Lehenga Choli",
    color: "Pink, Green",
    selling_price: "₹854",
    price: "₹2,099",
    disscount: "59% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/d/i/u/free-half-sleeve-big-tea-blue-trivety-original-imagnyd8rmf9cjqw.jpeg?q=70",
    brand: "Trivety",
    title: "Printed Semi Stitched Lehenga Choli",
    color: "Blue",
    selling_price: "₹479",
    price: "₹1,499",
    disscount: "68% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/l4u7vrk0/lehenga-choli/a/z/3/free-3-4-sleeve-jannat-maroon-jahal-fashion-original-imagfnap3f9zmnr3.jpeg?q=70",
    brand: "jahal fashion",
    title: "Self Design Semi Stitched Lehenga & Crop Top",
    color: "Red",
    selling_price: "₹424",
    price: "₹1,999",
    disscount: "78% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/f/c/9/s-short-sleeve-shset95212-shae-by-sassafras-original-imaghxqtcqfmxrur.jpeg?q=70",
    brand: "Shae by SASSAFRAS",
    title: "Embellished Stitched Lehenga Choli",
    color: "White",
    selling_price: "₹2,249",
    price: "₹4,999",
    disscount: "55% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/w/d/z/l-full-sleeve-shset95390-shae-by-sassafras-original-imagk4khzbgchqmn.jpeg?q=70",
    brand: "Shae by SASSAFRAS",
    title: "Embroidered Stitched Lehenga Choli",
    color: "Purple",
    selling_price: "₹1,934",
    price: "₹4,299",
    disscount: "55% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/j/e/6/free-sleeveless-new-designer-embroidred-sequins-heavy-work-original-imaggpy5gzt6m5hg.jpeg?q=70",
    brand: "ZAALIMA FASHION",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Dark Blue",
    selling_price: "₹784",
    price: "₹1,999",
    disscount: "60% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/kiw1dow0-0/lehenga-choli/d/d/a/free-half-sleeve-dulhen-7-lehenga-vm-tejani-original-imafykqgmxhzhf9y.jpeg?q=70",
    brand: "NJ FASHION",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Red",
    selling_price: "₹599",
    price: "₹3,999",
    disscount: "85% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/b/k/f/free-full-sleeve-lehenga-lehenga-for-women-lehenga-choli-net-original-imaggcvr8nhqehzf.jpeg?q=70",
    brand: "Cute Fellow",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Maroon",
    selling_price: "₹614",
    price: "₹3,499",
    disscount: "82% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/kvba7bk0/lehenga-choli/v/v/m/free-half-sleeve-new-ruffle-designer-lehenga-cholis-for-indian-original-imag88ryhq3gpupc.jpeg?q=70",
    brand: "ZAALIMA FASHION",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Grey",
    selling_price: "₹409",
    price: "₹1,999",
    disscount: "79% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/z/n/q/xs-sleeveless-shset95224-shae-by-sassafras-original-imaggjzgkvheh2ks.jpeg?q=70",
    brand: "Shae by SASSAFRAS",
    title: "Printed Stitched Lehenga Choli",
    color: "Maroon",
    selling_price: "₹1,919",
    price: "₹4,799",
    disscount: "60% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/j/p/i/xl-full-sleeve-shset95393-shae-by-sassafras-original-imagkmakcztfrrnf.jpeg?q=70",
    brand: "Shae by SASSAFRAS",
    title: "Printed Stitched Lehenga Choli",
    color: "Purple",
    selling_price: "₹2,114",
    price: "₹4,699",
    disscount: "55% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/krntoy80/lehenga-choli/z/n/8/free-3-4-sleeve-future-wine-goroly-original-imag5ezdwczgyb5m.jpeg?q=70",
    brand: "GOROLY",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Purple",
    selling_price: "₹792",
    price: "₹3,999",
    disscount: "80% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/kx6fwcw0/lehenga-choli/i/n/z/free-3-4-sleeve-kavya-lehengacholi-012-e-mart-original-imag9zx6ckfnthh5.jpeg?q=70",
    brand: "E mart",
    title: "Self Design Semi Stitched Lehenga Choli",
    color: "Pink",
    selling_price: "₹292",
    price: "₹599",
    disscount: "51% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/s/3/z/s-sleeveless-shset95191-shae-by-sassafras-original-imaghf5krhynk4zq.jpeg?q=70",
    brand: "Shae by SASSAFRAS",
    title: "Printed Stitched Lehenga & Crop Top",
    color: "Gold",
    selling_price: "₹1,679",
    price: "₹4,199",
    disscount: "60% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/kuzuoi80/lehenga-choli/g/4/f/m-short-sleeve-skdnew-age-7662-biba-original-imag7zn2xvyejmr3.jpeg?q=70",
    brand: "BIBA",
    title: "Printed Stitched Lehenga & Crop Top",
    color: "Dark Blue",
    selling_price: "₹4,800",
    price: "₹7,500",
    disscount: "36% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/kt7jv680/lehenga-choli/f/n/i/free-sleeveless-l8097-fashionuma-original-imag6hxffsx8hkgh.jpeg?q=70",
    brand: "anara",
    title: "Digital Print Semi Stitched Lehenga Choli",
    color: "Blue",
    selling_price: "₹599",
    price: "₹2,999",
    disscount: "80% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/9/f/e/free-3-4-sleeve-jivikaaa-001-vajiba-original-imaggzcgrycypkc7.jpeg?q=70",
    brand: "vajiba",
    title: "Solid Semi Stitched Lehenga Choli",
    color: "Maroon",
    selling_price: "₹357",
    price: "₹1,999",
    disscount: "82% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/k4k7f680/lehenga-choli/c/n/c/free-lc-sansa-shree-impex-original-imafnf74t3peacjm.jpeg?q=70",
    brand: "Shree Impex",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Dark Green",
    selling_price: "₹694",
    price: "₹5,999",
    disscount: "88% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/b/s/2/free-3-4-sleeve-future-morpankh-goroly-original-imag5ez6uxhvwreb.jpeg?q=70",
    brand: "GOROLY",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Blue",
    selling_price: "₹794",
    price: "₹3,999",
    disscount: "80% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/u/n/b/s-sleeveless-skdrose-bow8586-off-white-biba-original-imagmw9eza8rzrp6.jpeg?q=70",
    brand: "BIBA",
    title: "Printed Stitched Lehenga Choli",
    color: "White",
    selling_price: "₹8,995",
    price: "",
    disscount: "",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/o/x/n/free-na-lehngacholi-2-yuvi-creation-original-imaghgxcrdthfdy4.jpeg?q=70",
    brand: "Yuvi Creation",
    title: "Embellished Semi Stitched Lehenga Choli",
    color: "Light Blue",
    selling_price: "₹2,239",
    price: "₹3,900",
    disscount: "42% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/l19m93k0/lehenga-choli/r/r/3/free-short-sleeve-sb-velentine-s-b-creation-original-imagcvdgh5ptkwuq.jpeg?q=70",
    brand: "Anghanbrothers",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Red, Gold",
    selling_price: "₹952",
    price: "₹5,555",
    disscount: "82% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/n/u/v/free-sleeveless-new-designer-embroidred-sequins-heavy-work-original-imaggbwhhhnmhxxd.jpeg?q=70",
    brand: "ZAALIMA FASHION",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Purple",
    selling_price: "₹799",
    price: "₹3,399",
    disscount: "76% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/u/r/v/free-na-phoshak-25jan-12-yuvi-creation-original-imagmay6w9fy22fb.jpeg?q=70",
    brand: "Yuvi Creation",
    title: "Printed Semi Stitched Lehenga Choli",
    color: "Red, White",
    selling_price: "₹999",
    price: "₹1,900",
    disscount: "47% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/z/9/n/xl-sleeveless-skdfestive8249aw22fus-biba-original-imaggtzgkt83qbew.jpeg?q=70",
    brand: "BIBA",
    title: "Printed Stitched Lehenga Choli",
    color: "Pink",
    selling_price: "₹4,197",
    price: "₹5,995",
    disscount: "29% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/l37mtu80/lehenga-choli/c/u/h/free-3-4-sleeve-jannat-maroon02120-r-h-comapany-original-imagedyttdhzpz8j.jpeg?q=70",
    brand: "R&H COMAPANY",
    title: "Self Design Semi Stitched Lehenga & Crop Top",
    color: "Grey",
    selling_price: "₹339",
    price: "₹2,499",
    disscount: "86% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/g/k/8/free-3-4-sleeve-jivikaaa-001-vajiba-original-imaggzbbszb6m54n.jpeg?q=70",
    brand: "vajiba",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Red",
    selling_price: "₹349",
    price: "₹1,999",
    disscount: "82% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/m/q/7/free-half-sleeve-pochampalli-pattu-fabcartz-original-imaggvyj73udeg3h.jpeg?q=70",
    brand: "Fabcartz",
    title: "Self Design Semi Stitched Lehenga Choli",
    color: "Dark Green",
    selling_price: "₹999",
    price: "₹2,999",
    disscount: "66% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/d/i/u/free-half-sleeve-big-tea-blue-trivety-original-imagnyd8rmf9cjqw.jpeg?q=70",
    brand: "Trivety",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Blue",
    selling_price: "₹649",
    price: "₹2,699",
    disscount: "75% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/3/o/3/xl-sleeveless-shset95392-shae-by-sassafras-original-imagkmapsgbgup8r.jpeg?q=70",
    brand: "Shae by SASSAFRAS",
    title: "Floral Print Stitched Lehenga Choli",
    color: "Dark Blue",
    selling_price: "₹1,679",
    price: "₹4,199",
    disscount: "60% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/g/0/m/free-sleeveless-zip1434-zinariya-fab-original-imagnftyaaaqjexa.jpeg?q=70",
    brand: "Pink She",
    title: "Digital Print Semi Stitched Lehenga Choli",
    color: "Blue",
    selling_price: "₹460",
    price: "₹3,099",
    disscount: "85% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/f/g/b/free-3-4-sleeve-jivikaaa-001-vajiba-original-imaggzc8mespdkr6.jpeg?q=70",
    brand: "vajiba",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Blue",
    selling_price: "₹331",
    price: "₹1,999",
    disscount: "83% off",
    size: "",
  },
  {
    image:
      "https://rukminim1.flixcart.com/image/612/612/xif0q/lehenga-choli/g/x/s/free-full-sleeve-purple-lehenga-ishu-fab-original-imagnzgvgeq85gt8.jpeg?q=70",
    brand: "ISHU FAB",
    title: "Embroidered Semi Stitched Lehenga Choli",
    color: "Purple",
    selling_price: "₹711",
    price: "₹2,499",
    disscount: "71% off",
    size: "",
  },
];
